### ISSUE TITLE
Shareable Filter Link

### ISSUE THREAD

**Issue by H-K-47** [67au/OrnaCodex#2]
Is it possible to have shareable links of results? E.g. i wanted to share the Filter Event: Wyrmhunt and sent it to a friend to get all Boss/Raids for one specific event but the URL in the browser does not change.

BTW: Great Webservice!

**Comment by 67au** [comment]
Share link is old feature, and it needs some refactoring.

**Comment by 67au** [comment]
Finished at https://github.com/67au/OrnaCodex/commit/bce762423c7a75ddcf3b709ddc6759c9243c2a53

**Comment by H-K-47** [comment]
Thank you.

Has this been deployed already? I can't find the share button.

**Comment by 67au** [comment]
> Thank you.
> 
> Has this been deployed already? I can't find the share button.

auto update in the background
